"""Dependency-free Boolean/CNF constraint representations."""

from claasp.representations.constraints.sat.components import (
    BooleanFunctionalSATModel,
    BooleanNativeXorSATModel,
    DifferentialToTruncatedSATModel,
    ImpossibleBoundarySATModel,
    ModularAddDeterministicTruncatedSATModel,
    ModularAddDifferentialSATModel,
    ModularAddFunctionalSATModel,
    ModularAddLinearSATModel,
    ModularAddNativeXorSATModel,
    ModularAddNWindowSATModel,
    ModularAddSemiDeterministicTruncatedSATModel,
    ModularSubtractDeterministicTruncatedSATModel,
    ProbabilisticTruncatedModularAddSATModel,
    SBoxFunctionalSATModel,
    SBoxTransitionSATModel,
    SBoxXorDifferentialSATModel,
    SBoxXorLinearSATModel,
    TruncatedToLinearSATModel,
    WiringFunctionalSATModel,
)
from claasp.representations.constraints.sat.exporters import CryptoMiniSatDimacsExporter
from claasp.representations.constraints.sat.lowering import BooleanCNFModel, BooleanNativeXorModel
from claasp.representations.constraints.sat.model import CNFFormula, NativeXorCNFFormula
from claasp.representations.constraints.sat.trails import (
    NWindowSATStrategy,
    SemiDeterministicModularAddTransition,
    SharedDifferencePairedDifferentialLinearSATTrail,
    SharedDifferencePairedSATTrail,
    SharedDifferencePairedWordDifferentialLinearSATModel,
    SharedDifferencePairedWordDifferentialSATModel,
    SpeckImpossibleSATModel,
    SpeckImpossibleSATTrail,
    SpeckProbabilisticTruncatedSATModel,
    SpeckSemiDeterministicTruncatedSATModel,
    SpeckSemiDeterministicTruncatedTrail,
    WordDeterministicDifferentialLinearSATModel,
    WordDeterministicDifferentialLinearSATTrail,
    WordDeterministicTruncatedCharacteristic,
    WordDeterministicTruncatedEnumeration,
    WordDeterministicTruncatedNativeXorSATModel,
    WordDeterministicTruncatedSATModel,
    WordDifferentialNativeXorSATModel,
    WordDifferentialSATModel,
    WordLinearNativeXorSATModel,
    WordLinearSATModel,
)

__all__ = [
    "BooleanCNFModel",
    "BooleanNativeXorModel",
    "BooleanFunctionalSATModel",
    "BooleanNativeXorSATModel",
    "CNFFormula",
    "CryptoMiniSatDimacsExporter",
    "DifferentialToTruncatedSATModel",
    "ImpossibleBoundarySATModel",
    "ModularAddDifferentialSATModel",
    "ModularAddDeterministicTruncatedSATModel",
    "ModularAddFunctionalSATModel",
    "ModularAddLinearSATModel",
    "ModularAddNativeXorSATModel",
    "ModularAddNWindowSATModel",
    "ModularAddSemiDeterministicTruncatedSATModel",
    "ModularSubtractDeterministicTruncatedSATModel",
    "NWindowSATStrategy",
    "NativeXorCNFFormula",
    "ProbabilisticTruncatedModularAddSATModel",
    "SBoxFunctionalSATModel",
    "SBoxTransitionSATModel",
    "SBoxXorDifferentialSATModel",
    "SBoxXorLinearSATModel",
    "SpeckImpossibleSATModel",
    "SpeckImpossibleSATTrail",
    "SpeckProbabilisticTruncatedSATModel",
    "SemiDeterministicModularAddTransition",
    "SharedDifferencePairedSATTrail",
    "SharedDifferencePairedDifferentialLinearSATTrail",
    "SharedDifferencePairedWordDifferentialLinearSATModel",
    "SharedDifferencePairedWordDifferentialSATModel",
    "SpeckSemiDeterministicTruncatedSATModel",
    "SpeckSemiDeterministicTruncatedTrail",
    "TruncatedToLinearSATModel",
    "WiringFunctionalSATModel",
    "WordDeterministicTruncatedCharacteristic",
    "WordDeterministicDifferentialLinearSATModel",
    "WordDeterministicDifferentialLinearSATTrail",
    "WordDeterministicTruncatedEnumeration",
    "WordDeterministicTruncatedNativeXorSATModel",
    "WordDeterministicTruncatedSATModel",
    "WordDifferentialSATModel",
    "WordDifferentialNativeXorSATModel",
    "WordLinearSATModel",
    "WordLinearNativeXorSATModel",
]
