"""Generate the Sphinx index of every mechanically public v5 namespace."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "docs" / "public_api_namespaces.rst"
AUDIT_TOOL = ROOT / "tools" / "public_api_closure.py"


def public_modules() -> list[str]:
    """Return the deterministic public-module authority."""

    spec = importlib.util.spec_from_file_location("public_api_closure", AUDIT_TOOL)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load the public API closure tool")
    audit = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(audit)
    return audit.public_modules()


def render_reference(modules: list[str] | None = None) -> str:
    """Render all public modules as warning-free, non-duplicating autodoc entries."""

    modules = public_modules() if modules is None else modules
    lines = [
        ".. This file is generated by tools/generate_api_reference.py.",
        ".. Do not edit it by hand.",
        "",
    ]
    for module in modules:
        lines.extend(
            [
                module,
                "~" * len(module),
                "",
                f".. automodule:: {module}",
                "   :no-index:",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    modules = public_modules()
    DESTINATION.write_text(render_reference(modules), encoding="utf-8")
    print(f"wrote {DESTINATION.relative_to(ROOT)} with {len(modules)} public namespaces")


if __name__ == "__main__":
    main()
