"""Deterministic Python source compilation for typed primitive graphs."""

from base64 import b64encode
from hashlib import sha256

from claasp.graph import Primitive
from claasp.provenance import DriverIdentity, DriverKind
from claasp.representations.source.model import (
    SourceArtifact,
    SourceCompilationResult,
    SourceDiagnostic,
    SourceLanguage,
    SourceStatus,
)
from claasp.serialization import SerializationError, primitive_digest, serialize_primitive

PYTHON_COMPILER = DriverIdentity("claasp_python_source", DriverKind.COMPILER, "1")


def compile_python_source(primitive: Primitive) -> SourceCompilationResult:
    """Compile ``primitive`` to deterministic Python using registered semantics.

    The returned source has no filesystem side effects. It embeds canonical
    graph bytes and evaluates them through CLAASP's scalar oracle.


    EXAMPLES::

        >>> try:
        ...     compile_python_source()
        ... except TypeError:
        ...     print("required arguments rejected")
        required arguments rejected
    """

    if not isinstance(primitive, Primitive):
        raise TypeError("Python source compilation requires a Primitive")
    try:
        graph = serialize_primitive(primitive)
    except SerializationError as error:
        return SourceCompilationResult(
            SourceStatus.UNSUPPORTED,
            diagnostic=SourceDiagnostic(error.reason.value, str(error)),
        )
    encoded = b64encode(graph).decode("ascii")
    source = "\n".join(
        (
            '"""Generated by CLAASP; execute only through an explicit source driver."""',
            "from base64 import b64decode",
            "import json",
            "import sys",
            "from claasp.serialization import deserialize_primitive",
            "",
            f'_GRAPH = b64decode("{encoded}")',
            "PRIMITIVE = deserialize_primitive(_GRAPH)",
            "",
            "def evaluate(inputs):",
            "    result = PRIMITIVE.evaluate_with_trace(inputs)",
            "    order = (",
            "        tuple(PRIMITIVE.input_ports)",
            "        + tuple(item.component_id for item in PRIMITIVE.components)",
            "        + tuple(item.binding_id for item in PRIMITIVE.bindings)",
            "    )",
            "    return {",
            "        'output': None if result.output is None else list(result.output),",
            "        'values': [",
            "            {'source': source_id, 'value': list(result.values[source_id])}",
            "            for source_id in order",
            "        ],",
            "    }",
            "",
            "def main():",
            "    inputs = json.loads(sys.stdin.read())",
            "    sys.stdout.write(json.dumps(evaluate(inputs), separators=(',', ':'), sort_keys=True) + '\\n')",
            "",
            "if __name__ == '__main__':",
            "    main()",
            "",
        )
    )
    digest = sha256(source.encode("utf-8")).hexdigest()
    artifact = SourceArtifact(
        SourceLanguage.PYTHON,
        source,
        "primitive_evaluator.py",
        digest,
        primitive_digest(primitive),
        primitive.realization_identity,
        PYTHON_COMPILER,
    )
    return SourceCompilationResult(SourceStatus.READY, artifact=artifact)


__all__ = ["PYTHON_COMPILER", "compile_python_source"]
