"""Sage-independent typed core for the next major CLAASP release."""

from claasp_next.graph import (
    CompositeBuilder, CompositeDefinition, CompositeInstance, CompositeOutputs,
    Primitive, Component,
    InputVisibility, Port, PrimitiveInput, PrimitiveKind, Round, Selection,
    ValueType, public_input, secret_input,
)
from claasp_next.domains import BinaryExtensionField, Bit, PrimeField, Word
from claasp_next.representations.execution import (
    BatchEvaluationResult,
    BatchEvaluator,
    BatchExecutionDriver,
    EvaluationResult,
    ScalarEvaluator,
    ScalarExecutionDriver,
    TransposedBatchEvaluator,
    TransposedBatchExecutionDriver,
)
from claasp_next.encoding import bits_from_int, int_from_bits, int_from_units, units_from_int
from claasp_next.composites import (
    AESKeySchedule, AESRound, AESSubstitutionLayer, ChaChaQuarterRound, ParallelSBoxLayer,
)
from claasp_next.provenance import (
    DriverIdentity, DriverKind, ResultProvenance, TransformationRecord,
)
from claasp_next.transformations import (
    ComponentInverseRegistry, ComponentInverseSemantics, DEFAULT_INVERSE_REGISTRY,
    DependencyIndex, DependencySplit, GraphSource, GraphSourceKind,
    TransformationError, TransformationFailureReason, TransformationResult,
    inline_reorderings, invert_component, invert_primitive, partial_inverse,
    prune_orphans, reduce_rounds, remove_key_schedule,
    slice_primitive, slice_rounds, split_dependencies,
)

__all__ = [
    "BinaryExtensionField",
    "Bit",
    "BatchEvaluationResult",
    "BatchEvaluator",
    "BatchExecutionDriver",
    "AESKeySchedule",
    "AESRound",
    "AESSubstitutionLayer",
    "CompositeBuilder",
    "CompositeDefinition",
    "CompositeInstance",
    "CompositeOutputs",
    "ChaChaQuarterRound",
    "Primitive",
    "Component",
    "ComponentInverseRegistry",
    "ComponentInverseSemantics",
    "DEFAULT_INVERSE_REGISTRY",
    "EvaluationResult",
    "DriverIdentity",
    "DriverKind",
    "DependencyIndex",
    "DependencySplit",
    "GraphSource",
    "GraphSourceKind",
    "InputVisibility",
    "Port",
    "ParallelSBoxLayer",
    "PrimitiveInput",
    "PrimitiveKind",
    "PrimeField",
    "Round",
    "ResultProvenance",
    "TransformationError",
    "TransformationFailureReason",
    "TransformationRecord",
    "TransformationResult",
    "ScalarEvaluator",
    "ScalarExecutionDriver",
    "Selection",
    "TransposedBatchEvaluator",
    "TransposedBatchExecutionDriver",
    "ValueType",
    "Word",
    "bits_from_int",
    "int_from_bits",
    "int_from_units",
    "invert_component",
    "invert_primitive",
    "inline_reorderings",
    "partial_inverse",
    "prune_orphans",
    "units_from_int",
    "reduce_rounds",
    "remove_key_schedule",
    "slice_primitive",
    "slice_rounds",
    "split_dependencies",
    "public_input",
    "secret_input",
]
