"""Singular serialization for prime-field polynomial systems."""

from claasp_next.representations.constraints.polynomial.expression import Monomial, Polynomial
from claasp_next.representations.constraints.polynomial.system import PolynomialSystem


class SingularExporter:
    """Render a polynomial system as an executable Singular program.

    Variables are renamed to ``x0``, ``x1``, and so on. Comments retain the
    correspondence with CLAASP graph variables, avoiding restrictions on
    primitive and component identifiers in the external syntax.

    EXAMPLES::

        >>> from claasp_next.primitives import MiMC
        >>> from claasp_next.representations.constraints.polynomial import PrimeFieldPolynomialModel
        >>> from claasp_next.representations.constraints.polynomial.exporters import SingularExporter
        >>> system = PrimeFieldPolynomialModel(MiMC(17, 3, (1,))).polynomial_system()
        >>> program = SingularExporter().export(system)
        >>> program.splitlines()[0]
        '// Generated by CLAASP next; equations are generators of ideal I.'
        >>> 'ring r = 17,(x0,x1,x2,x3),dp;' in program
        True
    """

    def export(
        self,
        system: PolynomialSystem,
        *,
        ring_name: str = "r",
        ideal_name: str = "I",
        monomial_order: str = "dp",
    ) -> str:
        """Compute the export for this public typed contract."""

        if not isinstance(system, PolynomialSystem):
            raise TypeError("system must be a PolynomialSystem")
        for label, value in (
            ("ring_name", ring_name),
            ("ideal_name", ideal_name),
            ("monomial_order", monomial_order),
        ):
            if not self._is_identifier(value):
                raise ValueError(f"{label} must be a valid Singular identifier")

        external_names = tuple(f"x{index}" for index in range(len(system.variables)))
        name_mapping = dict(zip(system.variables, external_names))
        declarations = ",".join(external_names)
        equations = (
            ",\n  ".join(
                self._polynomial(polynomial, name_mapping) for polynomial in system.equations
            )
            or "0"
        )

        lines = [
            f"// Generated by CLAASP next; equations are generators of ideal {ideal_name}.",
        ]
        lines.extend(
            f"// {external_name} = {original_name}"
            for original_name, external_name in name_mapping.items()
        )
        lines.extend(
            [
                f"ring {ring_name} = {system.field.modulus},({declarations}),{monomial_order};",
                f"ideal {ideal_name} =",
                f"  {equations};",
                "",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def _is_identifier(value: object) -> bool:
        return (
            isinstance(value, str)
            and bool(value)
            and value.isascii()
            and value.replace("_", "a").isalnum()
            and not value[0].isdigit()
        )

    def _polynomial(self, polynomial: Polynomial, names: dict[str, str]) -> str:
        if not polynomial.terms:
            return "0"
        return "+".join(
            self._term(monomial, coefficient, names) for monomial, coefficient in polynomial.terms
        )

    def _term(self, monomial: Monomial, coefficient: int, names: dict[str, str]) -> str:
        factors = []
        if coefficient != 1 or not monomial.powers:
            factors.append(str(coefficient))
        for variable, exponent in monomial.powers:
            try:
                external_name = names[variable]
            except KeyError as error:
                raise ValueError(f"polynomial uses undeclared variable {variable!r}") from error
            factors.append(external_name if exponent == 1 else f"{external_name}^{exponent}")
        return "*".join(factors)
