"""Dependency-free contracts and adapters for result presentation."""

from claasp_next.presentation.adapters import (
    AdaptationResult,
    adapt_result,
    avalanche_section,
    catalogue_section,
    component_property_section,
    continuous_section,
    dieharder_section,
    neural_section,
    nist_section,
    trace_section,
    trail_section,
)
from claasp_next.presentation.composition import compose_report, present
from claasp_next.presentation.contracts import (
    Applicability,
    Citation,
    DiagnosticCode,
    EvidenceClass,
    ExecutionProvenance,
    MathematicalProvenance,
    PresentationDiagnostic,
    PresentationEvidence,
    PresentationProvenance,
    PrimitiveProvenance,
    ReproducibilityMetadata,
)
from claasp_next.presentation.dataframe import to_dataframe
from claasp_next.presentation.exports import (
    cell_data,
    render_csv_table,
    render_markdown_table,
    render_section,
    render_terminal_table,
    report_data,
    section_data,
    table_data,
)
from claasp_next.presentation.files import WrittenReport, render_report, write_report
from claasp_next.presentation.formatting import FormatSpec, ValueKind, format_value
from claasp_next.presentation.model import (
    Alignment,
    ReportData,
    ReportSection,
    Table,
    TableCell,
    TableColumn,
    TableRow,
)

__all__ = [
    "AdaptationResult",
    "Alignment",
    "Applicability",
    "Citation",
    "DiagnosticCode",
    "EvidenceClass",
    "ExecutionProvenance",
    "FormatSpec",
    "MathematicalProvenance",
    "PresentationDiagnostic",
    "PresentationEvidence",
    "PresentationProvenance",
    "PrimitiveProvenance",
    "ReportData",
    "ReportSection",
    "ReproducibilityMetadata",
    "Table",
    "TableCell",
    "TableColumn",
    "TableRow",
    "ValueKind",
    "WrittenReport",
    "adapt_result",
    "avalanche_section",
    "catalogue_section",
    "cell_data",
    "component_property_section",
    "compose_report",
    "continuous_section",
    "dieharder_section",
    "format_value",
    "neural_section",
    "nist_section",
    "present",
    "render_csv_table",
    "render_markdown_table",
    "render_report",
    "render_section",
    "render_terminal_table",
    "report_data",
    "section_data",
    "table_data",
    "to_dataframe",
    "trace_section",
    "trail_section",
    "write_report",
]
