#!/usr/bin/env python3
"""Recover semi-deterministic SAT clause templates from pinned legacy CLAASP."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    ROOT / "src/claasp/representations/constraints/sat/components/_semi_deterministic_templates.py"
)
SOURCE = Path("claasp/cipher_modules/models/sat/utils/utils.py")
SOURCE_SHA256 = "817ce0f3404f3b03a1d88769bdb88f7403f6991d1049af438395d78533784ce5"
FUNCTIONS = {
    0: "get_semi_deterministic_cnf_window_0",
    1: "get_cnf_semi_deterministic_window_1",
    2: "get_cnf_semi_deterministic_window_2",
    3: "get_cnf_semi_deterministic_window_3",
}


def _templates(source: Path):
    payload = source.read_bytes()
    if hashlib.sha256(payload).hexdigest() != SOURCE_SHA256:
        raise ValueError("legacy SAT utility does not match the reviewed commit")
    tree = ast.parse(payload)
    definitions = {
        node.name: node
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name in FUNCTIONS.values()
    }
    if set(definitions) != set(FUNCTIONS.values()):
        raise ValueError("legacy SAT utility is missing a reviewed window generator")
    recovered = {}
    for window, name in FUNCTIONS.items():
        node = definitions[name]
        if len(node.body) != 1 or not isinstance(node.body[0], ast.Return):
            raise ValueError(f"{name} is no longer a single static return expression")
        module = ast.Module(body=[node], type_ignores=[])
        ast.fix_missing_locations(module)
        namespace: dict[str, Any] = {}
        exec(compile(module, str(source), "exec"), {"__builtins__": {}}, namespace)
        arguments = tuple(argument.arg for argument in node.args.args)
        clauses = namespace[name](*arguments)
        allowed = set(arguments)
        tokenized = []
        for clause in clauses:
            tokens = tuple(clause.split())
            if not tokens or any(token.removeprefix("-") not in allowed for token in tokens):
                raise ValueError(f"{name} produced an unexpected literal")
            tokenized.append(tokens)
        recovered[window] = tuple(tokenized)
    return recovered


def _render(recovered) -> str:
    lines = [
        '"""Generated legacy semi-deterministic modular-add clause templates."""',
        "",
        "import json",
        "",
        "# Generated by tools/recover_sat_semi_deterministic_templates.py from",
        "# CLAASP commit 3aacc2758059de85682a9c6d0eda2cd75940e747.",
        f'SOURCE_SHA256 = "{SOURCE_SHA256}"',
        '_RAW_WINDOW_TEMPLATES = r"""',
        json.dumps(recovered, indent=2, sort_keys=True),
        '"""',
        "WINDOW_TEMPLATES = {",
        "    int(window): tuple(tuple(clause) for clause in clauses)",
        "    for window, clauses in json.loads(_RAW_WINDOW_TEMPLATES).items()",
        "}",
    ]
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("legacy_root", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    source = arguments.legacy_root / SOURCE
    rendered = _render(_templates(source))
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
