name: block-pr

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - develop

jobs:
  block-pr-to-main-from-not-develop:
    runs-on: ubuntu-latest
    if:
      (
      github.event.pull_request.head.ref  != 'develop' &&
      github.event.pull_request.base.ref == 'main'
      ) ||
      (
      github.event.pull_request.head.ref == 'main' &&
      github.event.pull_request.base.ref == 'develop'
      )
    steps:
      - name: Check branch name
        run: |
          if [ $GITHUB_HEAD_REF != "develop" ]; then
            echo "Pull request not allowed from branch $GITHUB_HEAD_REF to main."
            exit 1
          fi
