name: Run pytest for Forked projects

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - develop
      - main

concurrency:
  group: fork-run-pytest-tests_${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-pytest:
    if: ${{ github.event.repository.fork }}
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Run tests
      run: docker run --rm -v $PWD:/home/sage/claasp tiicrc/claasp-base:latest make github-pytest
