name: Generate and submit documentation
on:
  push:
    branches:
      - test/runner_scale_sets_for_ci

jobs:
  generate-documentation:
    # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
    runs-on: self-hosted-k3s
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Generate documentation
      run: make doc
