name: run-benchmark-tests
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - main

concurrency:
  group: run-benchmark-tests_${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-benchmark-tests:
    if: ${{ !github.event.repository.fork }}
    runs-on: self-hosted
    timeout-minutes: 3600
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Fix Directory Structure
      uses: ./.github/actions/fix-directory

    - name: Run pytest-benchmark
      run: |
            cd /home/runner/_work/claasp
            echo Running Benchmark tests
            make benchmark-tests