name: Run tests and SonarCloud Scan

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - develop
      - main

concurrency:
  group: run-pytest-tests_${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-doctest:
    if: ${{ !github.event.repository.fork }}
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Fix Directory Structure
      uses: ./.github/actions/fix-directory

    - name: Run doctest
      run: |
            cd /home/runner/_work/claasp
            make test
      env:
        GUROBI_COMPUTE_SERVER: ${{ secrets.GUROBI_COMPUTE_SERVER }}

  run-pytest:
    if: ${{ !github.event.repository.fork }}
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Fix Directory Structure
      uses: ./.github/actions/fix-directory

    - name: Run remote-pytest
      run: |
            cd /home/runner/_work/claasp
            make remote-pytest
      env:
        GUROBI_COMPUTE_SERVER: ${{ secrets.GUROBI_COMPUTE_SERVER }}

    - name: Upload Coverage.xml to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: /home/runner/_work/claasp/coverage.xml
        overwrite: true

  run-code-coverage:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Download Latest Coverage.xml from Artifacts
      uses: actions/download-artifact@v4
      with:
        name: coverage-report

    - name: Override Coverage Source Path for Sonar
      run: sed -i "s/<source>\/home\/runner\/_work\/claasp<\/source>/<source>\/github\/workspace\/claasp<\/source>/g" coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.branch.name=${{ env.GITHUB_HEAD_REF }}
          -Dsonar.python.coverage.reportPaths=coverage.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: run-pytest
