name: Run doctest

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - develop
      - main

concurrency:
  group: run-doctest_${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-doctest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Build doctest image
      run: |
        rm -rf build claasp.egg-info
        docker build -f docker/Dockerfile --target claasp-base -t claasp:doctest .

    - name: Run test in Docker
      run: |
        docker run --rm \
          -e PYTHONPATH=/home/sage/tii-claasp \
          --mount type=bind,source=${{ github.workspace }},target=/home/sage/tii-claasp \
          -w /home/sage/tii-claasp \
          claasp:doctest \
          sh -lc 'make install && make test'
      env:
        GUROBI_COMPUTE_SERVER: ${{ secrets.GUROBI_COMPUTE_SERVER }}
