name: Run doctest

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - develop
      - main

concurrency:
  group: run-doctest_${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-doctest:
    runs-on: self-hosted
    env:
      GUROBI_COMPUTE_SERVER: ${{ secrets.GUROBI_COMPUTE_SERVER }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Fix Directory Structure
      run: |
        mkdir /home/runner/_work/claasp_backup
        mv -f /home/runner/_work/claasp/claasp/* /home/runner/_work/claasp_backup
        rm -rf /home/runner/_work/claasp/
        mkdir /home/runner/_work/claasp
        mv -f /home/runner/_work/claasp_backup/* /home/runner/_work/claasp
        chmod g+w /home/runner/_work/claasp/ -R
        rm -rf /home/runner/_work/claasp_backup

    - name: Run test
      run: |
            cd /home/runner/_work/claasp
            make test