name: Run benchmark tests
on:
  push:
    branches:
      - 'performance-tests'
jobs:
  run-benchmark-tests:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 3600
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Print GITHUB_WORKSPACE
      run: |
          echo ${GITHUB_WORKSPACE}
          pwd
          ls -lah
    - name: Fix Directory Structure
      run: |
          mkdir /home/runner/_work/claasp_backup
          mv -f /home/runner/_work/claasp/claasp/* /home/runner/_work/claasp_backup
          rm -rf /home/runner/_work/claasp/
          mkdir /home/runner/_work/claasp
          mv -f /home/runner/_work/claasp_backup/* /home/runner/_work/claasp
          chmod g+w /home/runner/_work/claasp/ -R
          rm -rf /home/runner/_work/claasp_backup

    - name: Run pytest-benchmark
      run: |
            cd /home/runner/_work/claasp
            echo Running Benchmark tests
            make remote-benchmark-tests

    - name: Upload benchmarks folder to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: benchmark-report
        path: /home/runner/_work/claasp/.benchmarks

  push-benchmark-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download Latest benchmarks folder from Artifacts
        uses: actions/download-artifact@v2
        with:
          name: benchmark-report

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.AUTHORIZATION_TOKEN }}
          branch: 'performance-tests'
          message: "Add benchmark test results"
    needs: run-benchmark-tests