name: Run pytest and SonarCloud Scan

on:
  push:
    branches:
      - '**'

jobs:
  run-pytest-and-sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build
      uses: docker/build-push-action@v4
      id: built-image
      with:
        context: .
        file: ./docker/Dockerfile
        push: false
        load: true
        tags: claasp-lib
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Run tests
      run: docker run --rm -v $PWD:/home/sage/tii-claasp claasp-lib make remote-pytest

    - name: Override Coverage Source Path for Sonar
      run: sed -i "s/<source>\/home\/sage\/tii-claasp\/claasp<\/source>/<source>\/github\/workspace\/claasp<\/source>/g" coverage.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.branch.name=${{ env.GITHUB_HEAD_REF }}
          -Dsonar.python.coverage.reportPaths=coverage.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
