---
name: Run tests on arm64

on:
  push:
    branches:
      - devops/arm64-linux-support

concurrency:
  group: run-pytest-tests_${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-pytest-arm64:
    if: ${{ !github.event.repository.fork }}
    runs-on: arm64
    container:
      image: tiicrc/claasp-lib:develop-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run pytest
        run: |
          uname -a
          make remote-pytest
        env:
          GUROBI_COMPUTE_SERVER: ${{ secrets.GUROBI_COMPUTE_SERVER }}

  run-doctest-arm64:
    if: ${{ !github.event.repository.fork }}
    runs-on: arm64
    container:
      image: tiicrc/claasp-lib:develop-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run doctest
        run: |
          uname -a
          make test
        env:
          GUROBI_COMPUTE_SERVER: ${{ secrets.GUROBI_COMPUTE_SERVER }}
